---
- hosts: all
  become: yes
  vars:
    composer_version: 2.2.6
    php_version: "7.4"
    php_extensions:
      - php
      - php-cli
      - php-common
      - php-mysqlnd
      - php-curl
      - php-gd
      - php-ldap
      - php-mbstring
      - php-xml
      - php-bcmath
      - php-tokenizer
      - php-zip
      - php-intl
      - php-soap
      - php-fpm
    packages:
      - git
      - unzip
      - acl

  tasks:
    - name: Enable PHP 7.4 repository
      command: "amazon-linux-extras enable php{{ php_version }}"

    - name: Install PHP and extensions using shell (Amazon Linux 2)
      command: "yum install -y {{ item }}"
      loop: "{{ php_extensions }}"
      ignore_errors: yes

    - name: Install additional packages using shell (Amazon Linux 2)
      command: "yum install -y {{ item }}"
      loop: "{{ packages }}"
      ignore_errors: yes

    - name: Install Nginx using amazon-linux-extras
      command: "amazon-linux-extras install -y nginx1"
      ignore_errors: yes

    - name: Create a basic Nginx configuration file
      copy:
        content: |
          server {
              listen       80;
              server_name  localhost;

              location / {
                  root   /usr/share/nginx/html;
                  index  index.html index.htm;
              }

              error_page   500 502 503 504  /50x.html;
              location = /50x.html {
                  root   /usr/share/nginx/html;
              }
          }
        dest: /etc/nginx/conf.d/default.conf
        owner: root
        group: root
        mode: 0644

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: true
